// Generated by Selenium IDE
package pkgSeleniumDemo;
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class UibankautomationTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
		System.setProperty("webdriver.chrome.driver", "E:\\Seleniumsoftware\\chromedriver.exe");
		ChromeOptions options = new ChromeOptions();
//	    options.addArguments("incognito");
		options.addArguments("--remote-allow-origins=*");
		driver = new ChromeDriver(options);
		driver.manage().window().maximize();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void uibankautomation() throws InterruptedException {
    driver.get("https://uibank.uipath.com/");
   // driver.manage().window().setSize(new Dimension(1382, 736));
    driver.findElement(By.id("username")).click();
    driver.findElement(By.id("username")).sendKeys("ctrlaisoft");
    driver.findElement(By.id("password")).click();
    driver.findElement(By.id("password")).sendKeys("Uibank@1234");
    driver.findElement(By.xpath("//button[@type=\'submit\']")).click();
    Thread.sleep(5000);
    
    driver.findElement(By.xpath("/html/body/app-root/body/div/app-accounts/div/div[1]/div/div[1]/div[2]")).click();
   // driver.findElement(By.xpath("//div[2]")).click();
    Thread.sleep(5000);
    driver.findElement(By.id("accountNickname")).click();
    driver.findElement(By.id("accountNickname")).sendKeys("alexas");
    driver.findElement(By.id("typeOfAccount")).click();
    {
      WebElement dropdown = driver.findElement(By.id("typeOfAccount"));
      dropdown.findElement(By.xpath("//option[. = 'Savings']")).click();
    }
    driver.findElement(By.xpath("//button[contains(.,\'Apply\')]")).click();
    Thread.sleep(5000);
   System.out.println( driver.findElement(By.id("accountId")).getText());

      }
}
